version: "3"

services:
  nginx:
    build:
      context: ./nginx
    tty: true
    links:
      - node:node
    ports:
      - "80:80"

  node:
    build:
      context: ./node
    env_file:
      - ./.env
    volumes:
      - logs:/log/

volumes:
  logs:
###### To run docker-compose.dev.yml is development run the cmd:
# docker-compose up --build
